### ISSUE TITLE
Update internal state

### ISSUE THREAD

**Issue by terrakok** [Ahmad-Hamwi/lazy-pagination-compose#3]
It is not enough to have `appendPage` only.
The case:
 - server returns pages: `[a, a, a, b, c, c] [c, d, d, d, d, d] [e, f, ...]`
 - app should show the list: `a[3] b[1] c[3] d[5] e[1] ...`

for that I need to modify items after the next page is loaded.
When the first page is loaded the app shows
`a[3] b[1] c[2] {next page progress}`

When the second page is loaded the current last element should be updated:
`a[3] b[1] c[3] d[5] {next page progress}`
`             ^--new number here          `

**Comment by Ahmad-Hamwi** [comment]
Hello @terrakok , thank you for providing me such a use case

Thinking of the design that needs to be implemented for this case, I'm going to need to provide a setter that mutates the `allItems` field, and the state will stay as is (rendered loading and errors will stay rendered).

This means that you're gonna have to update the existing items first, then append the new page.

Your usage would look like this:

```kotlin
paginationState.allItems = a[3] b[1] c[3]
paginationState.appendPage(items = d[5], nextPageKey = .., isLastPage = ..)
```

But I'm not sure if this will cause unnecessary recompositions.

Another function that may be easeier for you to use and may skip some unnecessary recompositions is this one:

```kotlin
paginationState.setAllItemsWithAppendedPage(
    items = a[3] b[1] c[3] d[5],
    nextPageKey = ..,
    isLastPage = ..,
)
```

Once we agree on the design, I'll start implementing the functions and write the tests for them because there will be new scenarios that the library will go through.

I may also share snapshot versions of the library so that you can start using any initial implementations.

**Comment by Ahmad-Hamwi** [comment]
I have pushed version `1.3.6-SNAPSHOT` that contains the functionalities above.

It may take a while until changes are uploaded to Maven Central.

Let me know if everything works out well for you!

**Comment by terrakok** [comment]
```kotlin
val currentItems = paginationState.items
paginationState.applyNewState(
    allItems = ...,
    nextPageKey = ..,
    isLastPage = ..,
)
```
seems good

**Comment by Ahmad-Hamwi** [comment]
After testing out both ways unfortunately I'm gonna have to pass on the function that's easier for you and stick to the setter.

```kotlin
paginationState.allItems = a[3] b[1] c[3]
paginationState.appendPage(items = d[5], nextPageKey = .., isLastPage = ..)
```

This is because it may let the user go through unexpected scenarios when updating the `nextPageKey` and `isLastPage` in states such as Loading, and one of the goals of this library is not to confuse the user and go through such cases.

Also if I went with a function that forces the state to be loaded such as the `appendPage` but edits the full list, the naming of such function will also confuse users, or I gonna have to make one but add an experimental api annotation on top of it since its name can change.

I have published a snapshot version of the library, make sure to use it as follows:

```kotlin
repositories {
    ...
    mavenCentral {
        url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/")
    }
}
```

```toml
[versions]
lazy-pagination-compose = "1.3.5-SNAPSHOT"
```

Let me know if everything works out well for you

**Comment by terrakok** [comment]
I guess you meant "1.3.6-SNAPSHOT" :)
yes, it works, but it is really confusing. Because I did it:
```kotlin
paginationState.allItems = emptyList()
paginationState.appendPage(items = newItems, nextPageKey = .., isLastPage = ..)
```

**Comment by Ahmad-Hamwi** [comment]
Yes it is `1.3.6-SNAPSHOT`, sorry if you needed some time to figure this out..

Regarding the code, yes this is confusing.. You're doing this on the first page, Right?

**Comment by terrakok** [comment]
I do it for every page

**Comment by Ahmad-Hamwi** [comment]
I was expecting you to do:

```kotlin
onPageRequested { newData -> // [c, d, d, d, d, d]
    // allItems before are: a[3] b[1] c[3]
    paginationState.allItems = paginationState.allItems.map {...} // your logic to produce a[3] b[1] c[4]
    paginationState.appendPage(
        items = newList.map {...} // your logic to produce d[5]
    )
}
```

**Comment by Ahmad-Hamwi** [comment]
I'm not sure where your confusion is exactly, I would appreciate if you pinpointed it.

The complexity comes from your use case where you need to manipulate your data so that you update it correctly.

I told you that you will need to update the existing items first and then append then your new items, but I still don't understand why you're clearing the items first then setting it up back again. Is there something forcing you to do so?

Anyways I will be making an example project that is going to demonstrate how it should be used in the same example of yours provided initially.

**Comment by terrakok** [comment]
The confusion comes from the fact that I can do it different ways with the same result. In my case it is easier to build a final list of items instead of two: modified and new page. I don't see a reason to divide it.

**Comment by Ahmad-Hamwi** [comment]
I see so you're basically working around it, which makes sense.

I have uploaded `1.3.7-SNAPSHOT` that contains `appendPageWithUpdates(...)`

Let me know if it works out well for you.

**Comment by terrakok** [comment]
Yes. It works 👍:
```kotlin
val current = if (pageKey > firstPage) {
    allItems.associate { it.toPair() }.toMutableMap()
} else {
    mutableMapOf()
}
current.putAll(newItems.groupBy { it.itemId })
appendPageWithUpdates(
    allItems = current.entries.toList(),
    nextPageKey = pageKey + 1,
    isLastPage = newItems.isEmpty()
)
```

I'd recommend:
 - make the `paginationState.allItems` setter private
 - return `emptyList` if there is no items yet
 - might be rename `appendPageWithUpdates` method (up to you)

**Comment by Ahmad-Hamwi** [comment]
Good to hear, and thank you for your recommendations.

- I'll make the setter private back again, since it was confusing or users can work around it.
- This was also a change that I needed to make, but `emptyList` might mean zero data (data received, but page was empty), So I've gone with making the field nullable if there are no items yet. This going to be a breaking change that I should document in a new release.
- I am all about naming the function correctly and not confuse users, but to be honest naming this function is one of the hardest I came across and I'm still not convinced with its current name. I kept it experimental to warn users that it might change in the future, but I don't expect many people to use it either ways so I guess it's fine for now.
